const actionTypes = {
  LOAD_TMDB_CONFIG: 'LOAD_TMDB_CONFIG',
  LOAD_MOVIES: 'LOAD_MOVIES',
  SELECT_FILTER: 'SELECT_FILTER',
  LIST_MOVIES: 'LIST_MOVIES',
  RESET_MATCHES: 'RESET_MATCHES',
};

export default actionTypes;
